### ISSUE TITLE
Want to install python in system to use python shell

### ISSUE THREAD

**Issue by surendra-17** [AakashMallik/electron-load-balancer#7]
Not an issue doubt

**Comment by Pipe-Runner** [comment]
@surendra-17 Yes, you are right about that, you need to have python on your machine.

**Comment by surendra-17** [comment]
Thanks for your response 🤠 I have building desktop application(stock management) with electron  mysql need some tips

**Comment by Pipe-Runner** [comment]
@surendra-17 If u are going to use SQL engine then I would rather recomend u to use the native node module for Electron rather than using the python bridge. It would be far more simple.

**Comment by surendra-17** [comment]
Thanks for your help

**Comment by surendra-17** [comment]
Which native node module i have to use any recommandation

**Comment by surendra-17** [comment]
I want my db request in another process so its not affect my application performance

**Comment by Pipe-Runner** [comment]
@surendra-17 There are a couple of options to be honest. U can look into https://dev.to/abulhasanlakhani/connecting-to-sql-server-from-electron-react-1kdi

**Comment by surendra-17** [comment]
Thanks again bro its save my days i am searching for these from past two
weeks

**Comment by Pipe-Runner** [comment]
@surendra-17 No problem bro.
